version: 0.9.0.{build}
init:
- ps: Set-WinSystemLocale ja-JP
- ps: Restart-Computer
branches:
  except:
  - /topic\/.*/
  - original
configuration:
- Debug
- Debug_XP
- Release
- Release_XP
environment:
  BASE_CLASSES_URL:
    secure: aoYy8B0T541zQzc8iN8GeQ1IqEVi0YKPbzePTJ8R/I07c4uFi1ovamqlsdysFrJ92pz7J/6BxcJE+0Py0uSVPA==
before_build:
- ps: .\tools\before-build.ps1
build:
  project: src/TVTest_All.VS2013.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: .\tools\after-build.ps1
test: off
artifacts:
- path: pkg\*.zip
deploy: off
